### ISSUE TITLE
Introduce XML validation asserter

### ISSUE THREAD

**Issue by shulard** [shulard/atoum-xml-extension#1]
As mentioned on twitter, this extension must have XML validation asserters. There are different ways to validate :
- [x] DTD
- [x] Schema
- [x] RelaxNG

Each of them must be implemented as a different asserter.

**Comment by shulard** [comment]
For the moment they have been implemented as node asserters :
- `validateWithDTD($path)`
- `validateWithSchema($path)`
- `validateWithRelaxNG($path)`

Example here :

``` php
public function testSchemaValidation()
{
    $xml = <<<XML
<?xml version="1.0"?>
<root>
    <node/>
    <node>
        <subnode />
    </node>
</root>
XML;

    $this
        ->given(
            $path = realpath(__DIR__.'/../../../resources/node.xsd')
        )
        ->then
            ->xml($xml)
                ->validateWithSchema($path)
    ;
}
```

@jubianchi, is it the @atoum way to do that kind of things ?

It's also possible to introduce a new asserter `validate` with 3 methods `DTD`, `schema`, `relaxNG`. This second solution seems cleaner for me but introduces a new level in the asserter hierarchy...

**Comment by jubianchi** [comment]
@shulard your code example is exactly what we could find in a native asserter. 

If we were to introduce a new asserter I would make it look like:

``` php
<?php
$this
    ->schema->xsd($schema)->validates($xml)
    ->schema->dtd($schema)->validates($xml)
    ->schema->relaxNg($schema)->validates($xml)
;
```

Or we could go further and keep the validation in the `xml` asserter. Something like:

``` php
<?php
$this
    ->xml($xml)
        ->validates
            ->xsd($schema)
            ->dtd($schema)
            ->relaxNg($schema)
;
```

I'm pretty fine with any of these 3 solutions.

**Comment by shulard** [comment]
Thanks for your feedback !

I'm not comfortable with my too heavy `validatesWith...` syntax and prefer your latest example. I'll work on it asap 😄.

**Comment by jubianchi** [comment]
You could also make it clearer and more like other asserters in atoum:

``` php
<?php
$this
    ->xml($xml)
        ->isValidAgainstSchema
            ->xsd($schema)
            ->dtd($schema)
            ->relaxNg($schema)
;
```

**Comment by shulard** [comment]
Hello !

I've finally found a moment to work on that feature :smile:.

I've updated the syntax to use your `isValidAgainstSchema` idea, it's very clear to read now. I've also make it possible to use a simpler `validate` keyword to call `schema` asserter.

Now all the code is splitted in different files which tests for each ones... Thanks for your help here 👍.

If you want you can take a look at commit :  e05bec6
